### PR TITLE
Load sequencer state when new user connect  - Iss1

### PR DESCRIPTION
**Pull request by valou5940**
- State of the sequencer is stored server side

- Server transmits the state to new client on connection -> pads are activated

In the future, we should modify these fonction to dynamically activate the pads in case other tracks are created

Then I propose to open a new issue for adding tracks to the sequencer

### CODE REVIEW

**Comment by DerouineauNicolas** [comment]
Ok for me !

**Comment by xavierfav** [comment]
Please give a comprehensive title to the PR and reference the issue so that Github track it makes it easier to then follow the progression.

Reference the issue: #1 


Also, please take a look at for instance this blog post: [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/).

**Comment by xavierfav** [comment]
It's nice, good job!

A few comments:
- Is there any reason you store the messages in the map? It will be more logical to only store the ids of the activated pads. The information contained and sent in the map is redundant, it is not optimal.
- Would it be possible to follow a schema for the sequencer state as proposed in #1 ? Containing the keys corresponding to the nomenclature of the messages transmitted between clients?
- In _static/home.ejs_, why do we have one submit function per track? This cannot be generalized when we will get more tracks. And, I don't really understand why we need it. I also don't understand what is the form used for.

**Comment by DerouineauNicolas** [comment]
The PR is merged. @xavierfav Should we address your comments in a different issue/branch ?

**Pull request merged**
